name: Deploy Back

on:
  push:
    branches: ['main', 'backend']

permissions:
  contents: 'write'

jobs:
  deploy:
    # concurrency: ci-${{ github.ref }}
    # environment: prod
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Google Auth
        id: auth
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: Build
        run: gcloud builds submit backend --tag gcr.io/basic-words/server

        # docker build --tag gcr.io/basic-words/server backend/

      - name: Deploy
        run: gcloud run deploy server --image gcr.io/basic-words/server --platform managed --region us-central1 --allow-unauthenticated --port 8000